# Generated by Django 4.1.7 on 2024-02-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=120)),
                ("temp_cm", models.IntegerField()),
                ("temp_fm", models.IntegerField()),
            ],
        ),
    ]
